version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - QUEUE_TYPE=${QUEUE_TYPE:-none}
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379/0}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@localhost:5672/}
    volumes:
      - ./app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
